blank_issues_enabled: false
contact_links:
  - name: Support Server
    url: https://discord.com/channels/170995199584108546/872191259471671346
    about: The Earthdawn channel on the Official FoundryVTT Discord Server
  - name: Rules Discussion
    url: https://discord.com/channels/328545846935158785/328545930057875457
    about: You can discuss all things Earthdawn on the official Fasa Discord Server