name: Create release branch and update system manifest and changelog

env:
  NODE_VERSION: 22

on:
  workflow_dispatch:
    inputs:
      version:
        description: "What type of release is this? (major, minor, patch)"
        required: true
        default: "minor"
        options:
          - major
          - minor
          - patch

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js {{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Checkout main
        run: |
          git checkout main

      - name: Bump version
        id: bump_version
        run: |
          echo "version=$(npm --no-git-tag-version version ${{ github.event.inputs.version }})" >> $GITHUB_OUTPUT

      - name: Create release branch
        run: |
          git checkout -b release/${{ steps.bump_version.outputs.version }}

      - name: Update manifest version
        uses: TomaszKandula/variable-substitution@v1.0.2
        with:
          files: 'system.json'
        env:
          version: ${{ steps.bump_version.outputs.version }}

      - name: Commit changes
        run: |
          git add package.json package-lock.json system.json
          git commit -m "chore: prepare release ${{ steps.bump_version.outputs.version }}"