name: Release [1] - Prepare New Release
run-name: Bump ${{ inputs.version }} version and create release branch - Triggered by ${{ github.triggering_actor }}

env:
  NODE_VERSION: 22

on:
  workflow_dispatch:
    inputs:
      version:
        description: "What type of release is this? (major, minor, patch)"
        required: true
        default: "minor"
        options:
          - major
          - minor
          - patch

permissions:
    contents: write

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Set up Git
        run: |
          git config --global user.name "${{ vars.BOT_USER_NAME_GITHUB_ACTIONS }}"
          git config --global user.email "${{ vars.BOT_EMAIL_GITHUB_ACTIONS }}"
          git config --global push.autoSetupRemote true
          git config --global --list

      - name: Checkout main
        run: |
          git checkout main

      - name: Bump version
        id: bump_version
        run: |
          NEW_VERSION=$(npm --no-git-tag-version --tag-version-prefix "" version ${{ github.event.inputs.version }})
          if [[ -z "$NEW_VERSION" ]]; then
            echo "Failed to bump version."
            exit 1
          fi
          echo "::notice file=${{ github.workflow_ref }},line=50,title=New Version::Bumped version to $NEW_VERSION"
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Create release branch
        run: |
          BRANCH_NAME=release/${{ steps.bump_version.outputs.version }}
          git checkout -b $BRANCH_NAME
          git status

      - name: Load system id
        id: system_id
        uses: ActionsTools/read-json-action@main
        with:
          file_path: "./system.json"
          prop_path: "id"

      - name: Set up tag name
        id: set_tag_name
        run: |
          TAG_NAME=release-${{ steps.bump_version.outputs.version }}
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Update manifest version and release URLs
        uses: TomaszKandula/variable-substitution@v1.0.2
        with:
          files: 'system.json'
        env:
          version: ${{ steps.bump_version.outputs.version }}
          download: https://github.com/${{ github.repository }}/releases/download/${{ env.TAG_NAME }}/${{ steps.system_id.outputs.value }}-${{ env.TAG_NAME }}.zip

      - name: Commit changes
        run: |
          git add package.json package-lock.json system.json
          git commit -m "chore: prepare release ${{ steps.bump_version.outputs.version }}" \
            --trailer "Github-Workflow: ${{ github.workflow }}" \
            --trailer "Github-Workflow-Triggered-By: ${{ github.triggering_actor }}" \
            --trailer "Github-Workflow-Executed-By: ${{ github.actor }}" \
            --trailer "Github-Workflow-Run-ID: ${{ github.run_id }}"
          git push
