on:
  pull_request:
    types:
      - synchronize

jobs:
  build:
    if: false
    name: dummy release build
    runs-on: ubuntu-latest
    steps:
      - run: echo "dummy release build"

  push-to-foundry:
    if: false
    name: dummy push-to-foundry build
    runs-on: ubuntu-latest
    steps:
      - run: echo "dummy push-to-foundry build"